KrzysztofRozbicki/projekt-grupa-2

src/index.html
src/modern-normalize.css

Dodałem plik modern-normalize.css - do sprawdzenia i ewentualnego dodania/resetowania kolejnych domyślnych stylów.

Added modern-normalize.css

---

src/partials/about.html
src/sass/partials/_about.scss

add changes in html and scss

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss

html w header

---

src/partials/advantages.html
src/sass/partials/_advantages.scss

dodałem klasy znajdujące się w zmiennych to poszczególnych elementów, dodałem widok mobilny

added classes and media mobile

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss
src/sass/utils/_typography.scss

mobilka w headerze, dopisana klasa dla headerow w varaibles

mobile-header

---

src/partials/about.html
src/sass/partials/_about.scss

add pic to html + changes in scss

update html + scss

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss
src/sass/utils/_typography.scss

Wrzucony caly html i dodane style.
Klasa dla czcionki text-200 cos nie pasuje, pozniej zmienie.

almost done

---

src/partials/products.html
src/sass/partials/_products.scss

Hej, sorrki, że tak dużo, poprawię się na przyszłość :)
Zostały mi do dodania zdjęcia i zaraz będę poprawiać pozycje przycisków, żeby były responsywne.

html with css, no photos

---

src/partials/products.html
src/sass/partials/_products.scss

Dodałam obrazy w pseudoelementach, zgodnie z wytycznymi do zadania. Wersję mobilną sekcji Products uważam za zakończoną :)

Added photos in pseudoelements 

---

src/sass/partials/_products.scss

Jeszcze jeden pull request, żeby jutro nie było konfliktów ;) 
Dodałam ustawienia responsywne do wersji tabletowej, ale jeszcze nie ładowałam zdjęć.

Responsive version for tables - flexboxes, paddings etc., no photos yet

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss

nav, color, hovers

---

src/partials/customer-reviews.html
src/sass/partials/_customer-reviews.scss

Dodałem całą sekcję customer-reviews (do tej pory tylko część mobilna). Nie posiada szarych kropek na spodzie ze względu na slajder, który będzie dodany później.

Customer-reviews

---

src/sass/partials/_hero-header.scss

j.w. 
duzy circle zaslanial przy przejsciu opis.

kolko zaslanialo opis

---

src/partials/products.html
src/sass/partials/_products.scss

W sumie wszystko omówiliśmy na Slacku :)

Feature/products - responsive pictures for tablets and change of pseudo element location

---

src/sass/partials/_products.scss

Utworzyłam wersję desktopową, zdjęcia również są wgrane. Jest literówka w nazwie zdjęć - dekstop zamiast desktop, ale już tego nie zmieniałam. Jeżeli wszystko jest ok, to zostało mi jeszcze tylko to dodatkowe zadanie :)

Feature/products - finished desktop version

---

src/partials/about.html
src/sass/partials/_about.scss

+ add switch case @media for tablet;
+ add pos-relative for section about;
+ add pos-absolute for &__splash; +/- move "splash" image from container to section.

make some fixes and add switch case

---

src/sass/partials/_about.scss

fix desc-width

---

src/partials/products.html
src/sass/partials/_products.scss

Dodałam ,,szczegółowy opis produktu" po kliknięciu na przycisk oraz animację samego przycisku :)

Feature/products - added hover and focus button effects

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss
src/sass/utils/_animations.scss

Dodalem plik animations.scss
Animacja ikonki w buttonie.

animation file and svg animation

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss

picture, cienie i inne drobnostki

picture, final touches

---

src/partials/about.html
src/sass/partials/_about.scss

+change parent/child classes; +add retina controls; +items positioning

add tablet features

---

src/partials/advantages.html

dodałem modyfikator do klasy, uzupełniłem picture o brakujące retiny

rebuild html

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss
src/sass/utils/_animations.scss
src/sass/utils/_buttons.scss

popraweczki, polerowanko, dodane cienie do pozostalych buttonow

drobne poprawki

---

package-lock.json
package.json
src/js/slider.js
src/partials/customer-reviews.html
src/sass/main.scss
src/sass/modules/_effect-fade.scss
src/sass/modules/_pagination.scss
src/sass/modules/_swiper-vars.scss
src/sass/modules/_swiper.scss
src/sass/partials/_customer-reviews.scss

Zamiana ogólnego linkowania do wszystkich styli i skryptów na poszczególne moduły do slidera

Skrypt i moduły js dla slidera

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss

new burger

---

src/partials/gallery.html

Poprawienie <picture> żeby wyświetlało poprawną retine

---

src/partials/about.html
src/sass/partials/_about.scss

test - nie dodawaj do maina - to jest test po przypadkowym "twardym" wyłączeniu komputera :)

branch test

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss
src/sass/utils/_buttons.scss

Dodane linki do buttonów i przy okazji do ikonki

linki w buttonach i ikonce

---

src/partials/hero-header.html
src/sass/partials/_hero-header.scss
src/sass/utils/_animations.scss
src/sass/utils/_buttons.scss

animacje podczas loadowania i pare dopieszczen

animations when loading
